"""Build a clinical screening report PDF (fpdf2)."""

from __future__ import annotations

from fpdf import FPDF


def _ascii(text: str) -> str:
    """Helvetica core fonts are Latin-1; normalize common unicode."""
    return (
        (text or "")
        .replace("—", "-")
        .replace("–", "-")
        .replace("·", "|")
        .replace("×", "x")
        .encode("latin-1", "replace")
        .decode("latin-1")
    )


class ReportPDF(FPDF):
    def footer(self) -> None:
        self.set_y(-15)
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(100, 116, 139)
        self.cell(0, 10, f"NetraX clinical screening report - Page {self.page_no()}/{{nb}}", align="C")


def build_report_pdf(
    *,
    report_id: str,
    patient_id: str,
    patient_name: str,
    age: int | None,
    gender: str | None,
    center: str | None,
    severity: str,
    date: str,
    status: str,
    screening_id: str | None,
    confidence: float | None,
    referral_needed: bool | None,
    model_used: str | None,
) -> bytes:
    pdf = ReportPDF()
    pdf.alias_nb_pages()
    pdf.set_auto_page_break(auto=True, margin=18)
    pdf.add_page()

    pdf.set_font("Helvetica", "B", 18)
    pdf.set_text_color(15, 23, 42)
    pdf.cell(0, 10, "NetraX", new_x="LMARGIN", new_y="NEXT")
    pdf.set_font("Helvetica", "B", 14)
    pdf.cell(0, 8, "Diabetic Retinopathy Screening Report", new_x="LMARGIN", new_y="NEXT")
    pdf.set_font("Helvetica", "", 9)
    pdf.set_text_color(100, 116, 139)
    pdf.cell(0, 6, "AI-assisted clinical decision support - Confidential", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(2)
    pdf.set_draw_color(30, 41, 59)
    pdf.set_line_width(0.6)
    pdf.line(10, pdf.get_y(), 200, pdf.get_y())
    pdf.ln(8)

    pdf.set_font("Helvetica", "B", 10)
    pdf.set_text_color(79, 70, 229)
    pdf.cell(0, 6, _ascii(f"Report ID: {report_id}"), new_x="LMARGIN", new_y="NEXT")
    pdf.set_font("Helvetica", "", 9)
    pdf.set_text_color(71, 85, 105)
    pdf.cell(
        0,
        5,
        _ascii(f"Screening: {screening_id or '-'}  |  Date: {date}"),
        new_x="LMARGIN",
        new_y="NEXT",
    )
    pdf.ln(6)

    def section(title: str) -> None:
        pdf.set_font("Helvetica", "B", 11)
        pdf.set_text_color(15, 23, 42)
        pdf.cell(0, 7, title, new_x="LMARGIN", new_y="NEXT")
        pdf.ln(1)

    def row(label: str, value: str) -> None:
        pdf.set_font("Helvetica", "", 9)
        pdf.set_text_color(100, 116, 139)
        pdf.cell(48, 6, label)
        pdf.set_text_color(15, 23, 42)
        pdf.set_font("Helvetica", "B", 9)
        pdf.cell(0, 6, _ascii(value), new_x="LMARGIN", new_y="NEXT")

    section("Patient")
    row("Name", patient_name or "-")
    row("Patient ID", patient_id or "-")
    age_gender = " | ".join(
        p for p in [str(age) if age is not None else None, gender or None] if p
    ) or "-"
    row("Age / Gender", age_gender)
    row("Center", center or "-")
    pdf.ln(4)

    section("Screening Result")
    row("Severity", severity or "-")
    row("Status", status or "-")
    if confidence is not None:
        row("Confidence", f"{confidence:.2%}" if confidence <= 1 else f"{confidence:.2f}")
    if referral_needed is not None:
        row("Referable DR", "Yes" if referral_needed else "No")
    if model_used:
        row("Model", model_used)
    pdf.ln(4)

    section("AI Recommendation")
    pdf.set_font("Helvetica", "", 10)
    pdf.set_text_color(30, 41, 59)
    if referral_needed:
        rec = (
            "Ophthalmologist review recommended. "
            "Refer for comprehensive dilated fundus exam within clinical guidelines."
        )
    else:
        rec = "Routine follow-up; no urgent referral indicated based on AI triage."
    pdf.multi_cell(0, 5, rec)
    pdf.ln(6)

    section("Disclaimer")
    pdf.set_font("Helvetica", "I", 8)
    pdf.set_text_color(100, 116, 139)
    pdf.multi_cell(
        0,
        4.5,
        "This report is generated by NetraX as AI-assisted screening decision support. "
        "Final clinical interpretation and management decisions remain with the reviewing ophthalmologist.",
    )

    out = pdf.output()
    return bytes(out)
