import type { NavKey } from "@/shared/ui";

export const ROUTES: Record<NavKey, string> = {
  dashboard: "/dashboard",
  "new-screening": "/screening/new",
  patients: "/patients",
  screenings: "/screenings",
  reports: "/reports",
  analytics: "/analytics",
  quality: "/analytics/quality",
  simulation: "/simulation",
  users: "/users",
  centers: "/centers",
  devices: "/devices",
  settings: "/settings",
};

export const PATHS = {
  login: "/login",
  dashboard: "/dashboard",
  patientInfo: "/screening/new",
  imageUpload: "/screening/upload",
  workflow: "/screening/workflow",
  quality: "/screening/quality",
  enhancement: "/screening/enhancement",
  aiAnalysis: "/screening/ai-analysis",
  structure: "/screening/structure",
  lesions: "/screening/lesions",
  results: "/screening/results",
  gradcam: "/screening/gradcam",
  lesionEvidence: "/screening/lesion-evidence",
  modelCompare: "/screening/model-compare",
  evidenceSummary: "/screening/evidence-summary",
  review: "/screening/review",
  clinicalReport: "/reports/clinical",
  patientProfile: "/patients/profile",
  screeningHistory: "/screenings",
  reports: "/reports",
  analytics: "/analytics",
  modelPerformance: "/analytics/models",
  qualityAnalytics: "/analytics/quality",
  simulation: "/simulation",
  resourceAllocation: "/simulation/resources",
  centers: "/centers",
  devices: "/devices",
  operations: "/settings/operations",
  users: "/users",
  notifications: "/notifications",
  settings: "/settings",
  help: "/help",
  errors: "/system/errors",
  empty: "/system/empty",
  referral: "/screening/referral",
} as const;
